### ISSUE TITLE
[Feature] Attempted installation of `policycoreutils-python` RPM is incompatible with EL8 distros

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/watchmaker#2284]
Reference to [`policycoreutils-python` RPM](https://github.com/plus3it/watchmaker/blob/2118fb3de1c968d2253f6880eb312c63211bbe0a/src/watchmaker/workers/salt.py#L725) results in execution-errors (when attempting to install invalid package):
~~~
2022-09-16 17:53:57,923 [watchmaker.workers.base.SaltLinux][DEBUG][2200]: Command stdout: b'No match for argument: policycoreutils-python'
2022-09-16 17:53:57,935 [watchmaker.workers.base.SaltLinux][DEBUG][2200]: Command stdout: b'Package selinux-policy-targeted-3.14.3-95.el8_6.4.noarch is already installed.'
2022-09-16 17:53:57,937 [watchmaker.workers.base.SaltLinux][DEBUG][2200]: Command stdout: b'Package salt-minion-3005-1.el8.noarch is already installed.'
2022-09-16 17:53:57,978 [watchmaker.workers.base.SaltLinux][ERROR][2200]: Command stderr: b'Error: Unable to find a match: policycoreutils-python'
2022-09-16 17:53:58,073 [watchmaker.workers.base.SaltLinux][DEBUG][2200]: Command retcode: 1
2022-09-16 17:53:58,074 [watchmaker.workers.base.SaltLinux][CRITICAL][2200]: Command failed! Exit code=1, cmd=yum -y install policycoreutils-python selinux-policy-targeted salt-minion
2022-09-16 17:53:58,074 [watchmaker.Client][CRITICAL][2200]: Execution of the workers cadence has failed.
2022-09-16 17:53:58,074 [watchmaker][CRITICAL][2200]:
Traceback (most recent call last):
  File "/usr/local/bin/watchmaker", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/watchmaker/cli.py", line 110, in main
    sys.exit(watchmaker_client.install())
  File "/usr/local/lib/python3.6/site-packages/watchmaker/__init__.py", line 500, in install
    workers_manager.worker_cadence()
  File "/usr/local/lib/python3.6/site-packages/watchmaker/managers/worker_manager.py", line 59, in worker_cadence
    worker.install()
  File "/usr/local/lib/python3.6/site-packages/watchmaker/workers/salt.py", line 818, in install
    self._install_package()
  File "/usr/local/lib/python3.6/site-packages/watchmaker/workers/salt.py", line 767, in _install_package
    self._install_from_yum(self.yum_pkgs)
  File "/usr/local/lib/python3.6/site-packages/watchmaker/managers/platform.py", line 333, in _install_from_yum
    self.call_process(yum_cmd)
  File "/usr/local/lib/python3.6/site-packages/watchmaker/managers/platform.py", line 230, in call_process
    raise WatchmakerError(msg)
watchmaker.exceptions.WatchmakerError: Command failed! Exit code=1, cmd=yum -y install policycoreutils-python selinux-policy-targeted salt-minion
~~~
Need to update [`yum_pkgs` list](https://github.com/plus3it/watchmaker/blob/2118fb3de1c968d2253f6880eb312c63211bbe0a/src/watchmaker/workers/salt.py#L724-L728) to be conditionally-constructed based on distro.

**Comment by ferricoxide** [comment]
The `policycoreutils-python` package from pre-8 version of Red Hat Enterprise Linux (and clones)  has changed to `policycoreutils-python-utils`
